[workspace]
members = [
  ".",
  "capi",
  "cli",
]

[package]
name = "blazesym"
description = "blazesym is a library for address symbolization and related tasks."
version = "0.2.0-alpha.9"
edition = "2021"
rust-version = "1.65"
authors = ["Daniel Müller <deso@posteo.net>", "Kui-Feng <thinker.li@gmail.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/libbpf/blazesym"
readme = "README.md"
categories = [
  "algorithms",
  "api-bindings",
  "development-tools::debugging",
  "os::unix-apis",
  "value-formatting",
]
keywords = [
  "dwarf",
  "elf",
  "gsym",
  "stacktrace",
  "tracing",
]
exclude = ["data/kallsyms.xz"]
autobenches = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
  "backtrace",
  "demangle",
  "dwarf",
]
# Enable this feature to enable APK support (mostly relevant for
# Android).
apk = []
# Enable this feature to compile in support for capturing backtraces in errors.
# Note that by default backtraces will not be collected unless opted in with
# environment variables.
backtrace = []
# Enable this feature to get transparent symbol demangling.
demangle = ["cpp_demangle", "rustc-demangle"]
# Enable this feature to enable DWARF support.
dwarf = ["gimli"]
# Enable this feature to enable Gsym support.
gsym = []

# Below here are dev-mostly features that should not be needed by
# regular users.

# Enable this feature to opt in to the generation of unit test files.
# Having these test files created is necessary for running tests.
generate-unit-test-files = ["xz2", "zip"]
# Enable this feature to opt in to the generation of large benchmark
# files (also used for regression testing).
generate-large-test-files = ["reqwest", "xz2"]
# Disable generation of test files. This feature takes preference over
# `generate-unit-test-files`.
dont-generate-unit-test-files = []
# Enable code paths requiring a nightly toolchain. This feature is only meant to
# be used for testing and benchmarking purposes, not for the core library, which
# is expected to work on stable.
nightly = []

[[bench]]
name = "main"
harness = false

[profile.bench]
debug = true
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
cpp_demangle = {version = "0.4", optional = true}
gimli = {version = "0.28", optional = true}
libc = "0.2.137"
rustc-demangle = {version = "0.1", optional = true}
tracing = {version = "0.1", default-features = false, features = ["attributes"], optional = true}

[dev-dependencies]
# For performance comparison; pinned, because we use #[doc(hidden)]
# APIs.
addr2line = "=0.21.0"
anyhow = "1.0.71"
blazesym = {path = ".", features = ["generate-unit-test-files", "apk", "gsym", "tracing"]}
criterion = {version = "0.5.1", default-features = false, features = ["rayon", "cargo_bench_support"]}
env_logger = "0.10"
scopeguard = "1.2"
tempfile = "3.4"
test-log = {version = "0.2", default-features = false, features = ["trace"]}
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}

[build-dependencies]
libc = "0.2.137"
reqwest = {version = "0.11.18", optional = true, features = ["blocking"]}
xz2 = {version = "0.1.7", optional = true}
zip = {version = "0.6.4", optional = true, default-features = false}

# https://docs.rs/about/metadata
[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
