#ifndef __COMMON_PPM__
#define __COMMON_PPM__

#define EVENT_NEW_PROCESS_CREATED 201
#define EVENT_NEW_PACKET_DETECTED 202
#define EVENT_NEW_PACKET_PORT_MAPPED 203
#define ETHERNET_PAYLOAD_NOT_FOUND 100
#define IP_PAYLOAD_NOT_FOUND 101
#define TCP_PAYLOAD_NOT_FOUND 102
#define UDP_PAYLOAD_NOT_FOUND 103
#define PROTOCOL_NOT_IP 104
#define PROTOCOL_NOT_TCP_OR_UDP 105
#ifndef ETH_P_IP
#define ETH_P_IP 0x0800
#endif
#define AF_INET 2
#define AF_INET6 10

#define MAX_STR_LEN 512
#define MAX_CHRS MAX_STR_LEN
#define MAX_PROCESSES 1 << 16
#define TOTAL_PORTS 1 << 16
#define IPV6_ADDR_BYTE_COUNT 16
#define COMM_LENGTH
#endif